# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-23 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_invited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='agenda',
        ),
        migrations.AddField(
            model_name='activity',
            name='agendas',
            field=models.ManyToManyField(related_name='activities', to='trips.Agenda'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lat',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='lng',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='result',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
